# Site
name: "Dev Blog | Giacomo Lawrance"
title: "Dev Blog | Giacomo Lawrance"
description: "My dev blog, including random thoughts and ideas. I talk mainly about front end web development."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /blog
google_analytics: 'UA-57282086-5'
disqus: 'giacomolaw'
include: ["_pages"]
permalink: /:year/:month/:title/

# Authors
authors:
  giacomo:
    name: Giacomo Lawrance
    display_name: Giacomo
    gravatar: e81a9fa4c523f5f0e18522558b06ce4f
    email: thenerdystudent@gmail.com
    web: http://www.giacomolaw.me
    twitter: https://twitter.com/giacomolaw
    description: "Student and part time web developer."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-compose
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
